#' Reproducible class with environment and code.
#'
#' Reproducible class with environment and code.
#' @name qenv-class
#' @rdname qenv-class
#' @slot code (`expression`) to reproduce the environment
#' @slot code_dependency A `list` containing 3 elements
#' - `occurrence` - named `list` by object names with numeric vector as elements indicating calls in which object appears.
#' - `cooccurrence` - `list` of the same length as number of calls in `parsed_code`, containing `NULL`s if there is no
#' co-occurrence between objects, or a `character` vector indicating co-occurrence of objects in specific `parsed_code`
#' call element. If a character vector, then the first element is the name of the dependent object, and the rest are the
#' influencing objects
#' - `effects` - named `list`  by object names with numeric vector as elements indicating which calls has effect on this
#' object, or NULL if there are no side-effects pointing at this object.
#' @slot env (`environment`) environment which content was generated by the evaluation
#'  of the `code` slot.
#' @slot id (`integer`) random identifier of the code element to make sure uniqueness
#'  when joining.
#' @slot warnings (`character`) the warnings output when evaluating the code
#' @slot messages (`character`) the messages output when evaluating the code
#' @keywords internal
setClass(
  "qenv",
  slots = c(env = "environment", code = "expression", code_dependency = "list", id = "integer", warnings = "character", messages = "character"),
  prototype = list(
    env = new.env(parent = parent.env(.GlobalEnv)), code = expression(),
    code_dependency = list(occurrence = list(), cooccurrence = list(), effects = list()),
    id = integer(0), warnings = character(0), messages = character(0)
  )
)

#' It takes a `qenv` class and returns `TRUE` if the input is valid
#' @name qenv-class
#' @keywords internal
setValidity("qenv", function(object) {
  if (length(object@code) != length(object@id)) {
    "@code and @id slots must have the same length."
  } else if (length(object@code) != length(object@warnings)) {
    "@code and @warnings slots must have the same length"
  } else if (length(object@code) != length(object@messages)) {
    "@code and @messages slots must have the same length"
  } else if (length(object@code) != length(object@code_dependency$cooccurrence)) {
    "@code and @code_dependency$cooccurrence slots must have the same length"
  } else if (any(duplicated(object@id))) {
    "@id contains duplicated values."
  } else {
    TRUE
  }
})
