#' Reproducible class with environment and code.
#'
#' Reproducible class with environment and code.
#' @name Quosure-class
#' @rdname Quosure-class
#' @slot code (`expression`) to reproduce the environment
#' @slot env (`environment`) environment which content was generated by the evaluation
#'  of the `code` slot.
#' @slot id (`integer`) random identifier of the code element to make sure uniqueness
#'  when joining.
#' @keywords internal
setClass(
  "Quosure",
  slots = c(env = "environment", code = "expression", id = "integer"),
  prototype = list(env = new.env(parent = parent.env(.GlobalEnv)), code = expression(), id = integer(0))
)

#' It takes a `Quosure` class and returns TRUE if the input is valid
#' @name Quosure-class
#' @keywords internal
setValidity("Quosure", function(object) {
  if (length(object@code) != length(object@id)) {
    "@code and @id slots must have the same length."
  } else if (any(duplicated(object@id))) {
    "@id contains duplicated values."
  } else {
    TRUE
  }
})
