---
name:  Dependency Test 🔢

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  dependency-test:
    strategy:
      matrix:
        test-strategy: ["min", "release", "max"]
    uses: insightsengineering/r.pkg.template/.github/workflows/verdepcheck.yaml@add-r-min-deps-check-workflow
    name: Dependency Test - ${{ matrix.test-strategy }}
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      strategy: ${{ matrix.test-strategy }}
